print('This is a test')
print('I am practicing coding and committing')
print('Working with Git and Python together!')
print('I just need to remember how to use both lol')
print('')
print('This is more just nonsense')
print('So I can commit another update')