print('This is a test')
print('I am practicing coding and committing')
print('Working with Git and Python together!')
print('I just need to remember how to use both lol')
print('')
print('This is more just nonsense')
print('So I can commit another update')
print('Whyyyy doesnt it want to commit on here?')
print('')
print('Apparently I committed, it just didnt show up when I refreshed')

print('Ok lets try this again because I think I figured out my problem')
print('That didnt solve it, what about this?')